=== DefinitelyTyped/tsd/schema/cache-v1.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"description": "Track caching info for a single (hashed) request",
	"type": "object",
	"required": [
		"url",
		"key",
		"contentType",
		"httpETag",
		"httpModified",
		"cacheCreated",
		"cacheUpdated",
		"contentChecksum"
	],
	"properties": {
		"url": {
			"$ref": "#/definitions/uri"
		},
		"key": {
			"$ref": "#/definitions/sha1"
		},
		"contentType": {
			"$ref": "#/definitions/string"
		},
		"httpETag": {
			"$ref": "#/definitions/string"
		},
		"httpModified": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"cacheCreated": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"cacheUpdated": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"contentChecksum": {
			"$ref": "#/definitions/sha1"
		}
	},
	"definitions": {
		"string": {
			"type": "string"
		},
		"uri": {
			"type": "string",
			"pattern": "^https?:\/\/"
		},
		"sha1": {
			"type": "string",
			"pattern": "^[0-9a-f]{40}$"
		},
		"dateUTCISO": {
			"type": "string",
			"pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
		}
	}
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-raw-fmt1.0/3a/3ade19e775aa771afa43579727d13495e1502a0a.json
{
  "url": "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/chai/chai.d.ts",
  "key": "3ade19e775aa771afa43579727d13495e1502a0a",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:55.458Z",
  "cacheUpdated": "2014-06-21T04:11:58.057Z",
  "httpETag": "\"54d5770c97350ea0c2bab2b4a59ec64fbd200912\"",
  "httpModified": "2014-06-21T04:11:58.057Z",
  "contentChecksum": "a3c937d168f51e91b24061a09ab952ac7055c703"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-api-v3.0.0-fmt1.0/6b/6b90f59783451b80ac9b2aff9378cd79478dc0a7.json
{
  "url": "https://api.github.com/repos/DefinitelyTyped/DefinitelyTyped/git/trees/22033b203eaaaf7427f961d661407104268d1d81?recursive=1",
  "key": "6b90f59783451b80ac9b2aff9378cd79478dc0a7",
  "contentType": "application/json; charset=utf-8",
  "cacheCreated": "2014-06-21T04:08:51.565Z",
  "cacheUpdated": "2014-06-21T04:08:51.565Z",
  "httpETag": "\"fb53131c68724a886ad9f0aa2205dbe6\"",
  "httpModified": "2014-06-21T03:49:46.000Z",
  "contentChecksum": "2e087ec6b1a4d815ade563087a05706d85a10dd9"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-raw-fmt1.0/9a/9aedb9357f0e835ea1df6092ed4fedd5e793b126.json
{
  "url": "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/jquery/jquery.d.ts",
  "key": "9aedb9357f0e835ea1df6092ed4fedd5e793b126",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:54.355Z",
  "cacheUpdated": "2014-06-21T04:11:57.073Z",
  "httpETag": "\"6b4ebb68ae3a62d4ce4b57b9745fa3ea900067a5\"",
  "httpModified": "2014-06-21T04:11:57.073Z",
  "contentChecksum": "b4f13e5009bbd4185c2f01c29113a39f806aff6f"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/c0/c038a3295cd6fc9104b0acdfe260e5f28f4e7613.json
{
  "url": "https://api.github.com/repos/borisyankov/DefinitelyTyped/contents/bootstrap/bootstrap.d.ts?ref=master",
  "key": "c038a3295cd6fc9104b0acdfe260e5f28f4e7613",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:52.361Z",
  "cacheUpdated": "2014-06-21T04:11:55.329Z",
  "httpETag": "\"b9fe9cd59728baa3934a454c7bd979a46270b0bd\"",
  "httpModified": "2014-06-21T04:11:55.329Z",
  "contentChecksum": "c5aa93d7bd12a5e6aabe98ade2ff2262e9e40f44"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-raw-fmt1.0/11/1166d8058295930735943069d75369fd520c8a76.json
{
  "url": "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/bootstrap/bootstrap.d.ts",
  "key": "1166d8058295930735943069d75369fd520c8a76",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:52.361Z",
  "cacheUpdated": "2014-06-21T04:11:55.329Z",
  "httpETag": "\"b9fe9cd59728baa3934a454c7bd979a46270b0bd\"",
  "httpModified": "2014-06-21T04:11:55.329Z",
  "contentChecksum": "c5aa93d7bd12a5e6aabe98ade2ff2262e9e40f44"
}
