=== DefinitelyTyped/tsd/schema/cache-v1.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"description": "Track caching info for a single (hashed) request",
	"type": "object",
	"required": [
		"url",
		"key",
		"contentType",
		"httpETag",
		"httpModified",
		"cacheCreated",
		"cacheUpdated",
		"contentChecksum"
	],
	"properties": {
		"url": {
			"$ref": "#/definitions/uri"
		},
		"key": {
			"$ref": "#/definitions/sha1"
		},
		"contentType": {
			"$ref": "#/definitions/string"
		},
		"httpETag": {
			"$ref": "#/definitions/string"
		},
		"httpModified": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"cacheCreated": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"cacheUpdated": {
			"$ref": "#/definitions/dateUTCISO"
		},
		"contentChecksum": {
			"$ref": "#/definitions/sha1"
		}
	},
	"definitions": {
		"string": {
			"type": "string"
		},
		"uri": {
			"type": "string",
			"pattern": "^https?:\/\/"
		},
		"sha1": {
			"type": "string",
			"pattern": "^[0-9a-f]{40}$"
		},
		"dateUTCISO": {
			"type": "string",
			"pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$"
		}
	}
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/94/9475d358a03312943fd546c6b7ce2f74748514d0.json
{
  "url": "https://api.github.com/repos/borisyankov/DefinitelyTyped/contents/jquery/jquery.d.ts?ref=master",
  "key": "9475d358a03312943fd546c6b7ce2f74748514d0",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:54.355Z",
  "cacheUpdated": "2014-06-21T04:11:57.073Z",
  "httpETag": "\"6b4ebb68ae3a62d4ce4b57b9745fa3ea900067a5\"",
  "httpModified": "2014-06-21T04:11:57.073Z",
  "contentChecksum": "b4f13e5009bbd4185c2f01c29113a39f806aff6f"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/e3/e3d1da4866566e7f76b749c2d9eaed015638f6c1.json
{
  "url": "https://raw.github.com/borisyankov/DefinitelyTyped/master/chai/chai.d.ts",
  "key": "e3d1da4866566e7f76b749c2d9eaed015638f6c1",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:55.458Z",
  "cacheUpdated": "2014-06-21T04:11:58.057Z",
  "httpETag": "\"54d5770c97350ea0c2bab2b4a59ec64fbd200912\"",
  "httpModified": "2014-06-21T04:11:58.057Z",
  "contentChecksum": "a3c937d168f51e91b24061a09ab952ac7055c703"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/bd/bd6bd1beef3497d75dcfdb27dfb5c041b045c50c.json
{
  "url": "https://api.github.com/repos/borisyankov/DefinitelyTyped/contents/async/async.d.ts?ref=master",
  "key": "bd6bd1beef3497d75dcfdb27dfb5c041b045c50c",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:50.808Z",
  "cacheUpdated": "2014-06-21T04:11:53.749Z",
  "httpETag": "\"25736941fe8de2b32cd354004c3737892b74acf4\"",
  "httpModified": "2014-06-21T04:11:53.749Z",
  "contentChecksum": "190840176d4765445169bf62a81163c97696819c"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-api-v3.0.0-fmt1.0/99/9980d37b117f1045694ad54fa08a55830e296499.json
{
  "url": "https://api.github.com/repos/DefinitelyTyped/DefinitelyTyped/branches/master",
  "key": "9980d37b117f1045694ad54fa08a55830e296499",
  "contentType": "application/json; charset=utf-8",
  "cacheCreated": "2014-06-21T03:12:48.208Z",
  "cacheUpdated": "2014-06-21T04:08:50.639Z",
  "httpETag": "\"00a84587c2b8fda51c10b7a80cb0f6a5\"",
  "httpModified": "2014-06-21T04:08:50.639Z",
  "contentChecksum": "54549545c41c30584977ef32c8fa1b841442464c"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-api-v3.0.0-fmt1.0/23/2317caa92ea3c2a2c942f69c4fb8ebb40237974c.json
{
  "url": "https://api.github.com/repos/DefinitelyTyped/DefinitelyTyped/commits?path=async%2Fasync.d.ts",
  "key": "2317caa92ea3c2a2c942f69c4fb8ebb40237974c",
  "contentType": "application/json; charset=utf-8",
  "cacheCreated": "2014-06-21T03:12:49.761Z",
  "cacheUpdated": "2014-06-21T04:08:52.314Z",
  "httpETag": "\"f0d1665bf3010b02ff11095a8a83fa23\"",
  "httpModified": "2014-06-07T09:57:20.000Z",
  "contentChecksum": "f6643d830e70d24d7e27063b6d96417092269db7"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/borisyankov-DefinitelyTyped/git-raw-fmt1.0/f7/f74eeece0a10c145464cec52f43e9ea3d72e75c5.json
{
  "url": "https://api.github.com/repos/borisyankov/DefinitelyTyped/contents/chai/chai.d.ts?ref=master",
  "key": "f74eeece0a10c145464cec52f43e9ea3d72e75c5",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:55.458Z",
  "cacheUpdated": "2014-06-21T04:11:58.057Z",
  "httpETag": "\"54d5770c97350ea0c2bab2b4a59ec64fbd200912\"",
  "httpModified": "2014-06-21T04:11:58.057Z",
  "contentChecksum": "a3c937d168f51e91b24061a09ab952ac7055c703"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-api-v3.0.0-fmt1.0/05/0562698464ba60434bb2b01f3b2dda4f25519758.json
{
  "url": "https://api.github.com/repos/DefinitelyTyped/DefinitelyTyped/git/trees/69e3f7383790601cd1fb7d6c674a127e43b23dce?recursive=1",
  "key": "0562698464ba60434bb2b01f3b2dda4f25519758",
  "contentType": "application/json; charset=utf-8",
  "cacheCreated": "2014-06-21T03:12:49.070Z",
  "cacheUpdated": "2014-06-21T03:36:49.444Z",
  "httpETag": "\"a0bc16464c0348166514b9db918b0506\"",
  "httpModified": "2014-06-20T13:14:41.000Z",
  "contentChecksum": "a0759b8106a41810fd2e27abfa3ff5cb70ca929b"
}

=== DefinitelyTyped/tsd/test/fixtures/tsd-cache/DefinitelyTyped-DefinitelyTyped/git-raw-fmt1.0/22/2271dafd800fb0437db21c63217a3ba8407b7c55.json
{
  "url": "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/async/async.d.ts",
  "key": "2271dafd800fb0437db21c63217a3ba8407b7c55",
  "contentType": "video/mp2t",
  "cacheCreated": "2014-06-21T03:12:50.808Z",
  "cacheUpdated": "2014-06-21T04:11:53.749Z",
  "httpETag": "\"25736941fe8de2b32cd354004c3737892b74acf4\"",
  "httpModified": "2014-06-21T04:11:53.749Z",
  "contentChecksum": "190840176d4765445169bf62a81163c97696819c"
}
