=== DefinitelyTyped/tsd/schema/tsd-v4.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "tsd-v4-dev-5",
	"description": "TSD - TypeScript Definition Manager: config & data file",
	"type": "object",
	"required": ["version", "repo", "ref", "path"],
	"properties": {
		"version": {
			"description": "config-format version",
			"type": "string",
			"pattern": "^v[\\d]+$"
		},
		"path": {
			"description": "path to definition directory",
			"type": "string",
			"minLength": 1
		},
		"repo": {
			"description": "github repository \"owner/name\"",
			"type": "string",
			"pattern": "^[\\w\\.-]+/[\\w\\.-]+$"
		},
		"ref": {
			"description": "git index ref (branch/commit)",
			"type": "string",
			"pattern": "^[\\w\\.-]+(?:\\/[\\w\\.-]+)*$"
		},
		"cache": {
			"description": "path to (shared) tsd-cache",
			"type": "string",
			"minLength": 1
		},
		"bundle": {
			"description": "path to <reference /> bundle",
			"type": "string",
			"pattern": "\\w+\\.ts$"
		},
		"stats": {
			"description": "enable stats tracking",
			"type": "boolean"
		},
		"installed": {
			"description": "index of installed definitions",
			"type": "object",
			"additionalProperties": false,
			"patternProperties": {
				"^[\\w\\.-]+\\/[\\w\\.-]+\\.d\\.ts$": {
					"type": "object",
					"required": ["commit"],
					"properties": {
						"commit": {
							"description": "sha1 hex",
							"type": "string",
							"pattern": "^[0-9a-f]{6,40}$"
						}
					}
				}
			}
		}
	}
}

=== DefinitelyTyped/tsd/test/spec/api/fixtures/expected/install/bootstrap/tsd.json
{
  "version": "v4",
  "repo": "DefinitelyTyped/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "bootstrap/bootstrap.d.ts": {
      "commit": "0545e0567d242abcd295a63babb86c88e7d9911d"
    },
    "jquery/jquery.d.ts": {
      "commit": "0545e0567d242abcd295a63babb86c88e7d9911d"
    }
  }
}

=== DefinitelyTyped/tsd/test/nspec/cases/reinstall-clean-should-remove-unreferenced-3/setup/tools/tsd.json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "jquery/jquery.d.ts": {
      "commit": "13397478ef869824f6cf5c750c49dbe4ece9622e"
    },
    "node/node.d.ts": {
      "commit": "13397478ef869824f6cf5c750c49dbe4ece9622e"
    },
    "qunit/qunit.d.ts": {
      "commit": "13397478ef869824f6cf5c750c49dbe4ece9622e"
    }
  }
}

=== DefinitelyTyped/tsd/test/nspec/cases/install-_debugger/expected/tsd.json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "_debugger/_debugger.d.ts": {
      "commit": "5937bdd91a0f45a6d4c2f8a5692990fbce573764"
    },
    "node/node.d.ts": {
      "commit": "d2bab5738b84b91d8ee18a68c7b379a9714cf82f"
    }
  }
}

=== DefinitelyTyped/tsd/test/nspec/cases/jquery-qunit-install/expected/tsd.json
{
  "version": "v4",
  "repo": "DefinitelyTyped/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "jquery/jquery.d.ts": {
      "commit": "f7cfda9f1a6d4de9953f23db03fd5095ac216d41"
    },
    "qunit/qunit.d.ts": {
      "commit": "e0dac065a35c99287e2608ba39e9568c993ff0f6"
    }
  }
}

=== DefinitelyTyped/tsd/tsd.json
{
	"version": "v4",
	"path": "./typings",
	"repo": "DefinitelyTyped/DefinitelyTyped",
	"ref": "master",
	"bundle": "./typings/tsd.d.ts",
	"stats": false,
	"installed": {
		"universal-analytics/universal-analytics.d.ts": {
			"commit": "5e32785f26f69662a6b2b378bd3d54f062821527"
		},
		"mocha/mocha.d.ts": {
			"commit": "eed8736e6445ab77cf91a0f03302f5e74320c9be"
		},
		"node/node.d.ts": {
			"commit": "88f38f5b582007f8a4e71cb9023f8a2daa98fbb7"
		},
		"semver/semver.d.ts": {
			"commit": "b2e96a424672735fcd74fc989d1092386cbe082f"
		},
		"bluebird/bluebird.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"lazy.js/lazy.js.d.ts": {
			"commit": "4f75bef422dbb8564cc52a05d3d37665a638175f"
		},
		"detect-indent/detect-indent.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"exit/exit.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"jsesc/jsesc.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"json-pointer/json-pointer.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"minimist/minimist.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"open/open.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"source-map-support/source-map-support.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"mkdirp/mkdirp.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"uri-templates/uri-templates.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"configstore/configstore.d.ts": {
			"commit": "16c0f2c75a30cace4d673b363bbe7af2fe31cc86"
		},
		"joi/joi.d.ts": {
			"commit": "c63244f8bae7725f100a0b8a9a255305a990f6c6"
		},
		"glob/glob.d.ts": {
			"commit": "7573f56bec703a373ab307eeeb23aa0e0b4ee10f"
		},
		"minimatch/minimatch.d.ts": {
			"commit": "7573f56bec703a373ab307eeeb23aa0e0b4ee10f"
		},
		"request/request.d.ts": {
			"commit": "a9d2023e8eb1afe534b55758f2f1d16fb69ce61f"
		},
		"form-data/form-data.d.ts": {
			"commit": "a9d2023e8eb1afe534b55758f2f1d16fb69ce61f"
		},
		"bl/bl.d.ts": {
			"commit": "0de1592ef9e3144b925287ca0494f621e12b01c6"
		},
		"rimraf/rimraf.d.ts": {
			"commit": "4c09ca98bb22e3fa6964d8d27b9a359e54f9d83c"
		},
		"lru-cache/lru-cache.d.ts": {
			"commit": "ff4d52f8edf4f65fcb15ff129ea8861e93417c87"
		},
		"lockfile/lockfile.d.ts": {
			"commit": "6745ac3279f3650a8ce5e8877cca831272fe0a06"
		},
		"deep-freeze/deep-freeze.d.ts": {
			"commit": "83663818b8176edfe1343e6d7eff688fb1375949"
		},
		"ncp/ncp.d.ts": {
			"commit": "83663818b8176edfe1343e6d7eff688fb1375949"
		},
		"type-detect/type-detect.d.ts": {
			"commit": "47ebd394626861a9d492a7eac1f6aca96df6dfc1"
		},
		"chai/chai.d.ts": {
			"commit": "5a8f9e312f3db37b8efc4dcdd1de204f60e67eb1"
		},
		"chalk/chalk.d.ts": {
			"commit": "e1182d56ccb192379eade6055d9ba3fb6a0bacc4"
		}
	}
}

=== DefinitelyTyped/tsd/test/nspec/cases/install-command-without-args-3/expected/tsd.json
{
  "version": "v4",
  "repo": "borisyankov/DefinitelyTyped",
  "ref": "master",
  "path": "typings",
  "bundle": "typings/tsd.d.ts",
  "installed": {
    "atom/atom.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "q/Q.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "space-pen/space-pen.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "emissary/emissary.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "mixto/mixto.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "pathwatcher/pathwatcher.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "node/node.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "text-buffer/text-buffer.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "status-bar/status-bar.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    },
    "jquery/jquery.d.ts": {
      "commit": "066819c65ff561ca109955e0b725c253e243f0a2"
    }
  }
}
